# Generated by Django 5.0.1 on 2024-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.FloatField(default='199'),
        ),
    ]
