# Generated by Django 5.0.1 on 2024-03-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicX', '0003_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='song',
            new_name='songs',
        ),
    ]
