# Generated by Django 5.0.1 on 2024-03-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicX', '0004_rename_song_download_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='order_at',
            new_name='download',
        ),
    ]
